config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :users
  
  match '/signup', :to => 'users#new'

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  
  root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  encrypted_password :string(255)
#  salt               :string(255)
#

require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  email_regex = /\A[\w+\-._]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true, :length => {:maximum => 50}
  validates :email, :presence => true, :format => {:with => email_regex}, :uniqueness => {:case_sensitive => false}
  
  # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence  => true, :confirmation => true, :length => {:within => 6..40}
  
  before_save :encrypt_password
  
  #Return if use's password is same as submitted password
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  private 
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
   @user = User.find(params[:id])
   @title = @user.name
  end
  def new
    @user = User.new
    @title = "Sign Up"
  end
 def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
      else
      @title = "Sign up"
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Return a title on a per-page basis.
  def title
    base_title="Ruby on Rails Tutorial Sample App"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
  gravatar_image_tag(user.email.downcase, :alt => user.name,
                                          :class => 'gravatar',
                                          :gravatar => options)
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<nav class="container">
		<ul class="footer-links">
			<li>
				<%= link_to "About", about_path %>
			</li>
			<li>
				<%= link_to "Contact", contact_path %>
			</li>
			<li>
				<a href="http://news.railstutorial.org/">News</a>
			</li>
			<li>
				<a href="http://www.railstutorial.org/">Rails Tutorial</a>
			</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> 
				<span class="icon-bar"></span> 
				<span class="icon-bar"></span> 
				<span class="icon-bar"></span> 
			</a>
			<!--% logo = image_tag("logo.png", :alt => "HourGlass") %-->
			<%= link_to "HourGlass", root_path, :class=> "logo" %>

			<div class="nav-collapse pull-right">
				<ul class="nav">
					<li>
						<%= link_to "Home", root_path %>
					</li>
					<li>
						<%= link_to "Help", help_path %>
					</li>
					<li>
						<%= link_to "Sign in", "#" %>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'bootstrap', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<style type="text/css">

</style>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<html>
	<head>
		<title><%= title %></title>
		<%= csrf_meta_tag %>
		<!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<%= render 'layouts/stylesheets'%>
		<link href='http://fonts.googleapis.com/css?family=Lato|Ubuntu' rel='stylesheet' type='text/css'>
	</head>
	<body>
		
			<%= render 'layouts/header'%>
			<div class="container container-fluid">
				<% flash.each do |key, value| %>
					<div class="alert alert-success <%= key %>">
						<button type="button" class="close" data-dismiss="alert">×</button>
						<%= value %>
					</div>
				<% end %>
				<%= yield %>
			</div>
				<%= render 'layouts/footer'%>
			
			<%= debug(params) if Rails.env.development? %>
			<!-- Placed at the end of the document so the pages load faster -->
			<%= javascript_include_tag 'jquery-1.7.2.min' %>
			<%= javascript_include_tag 'bootstrap.min' %>
	</body>
</html>

app/views/pages/about.html.erb
<h1><%= @title%></h1>
<p>
	Contact Ruby on Rails Tutorial about the sample app at the
	<a href="http://railstutorial.org/feedback">feedback page</a>.
</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1><%= @title%></h1>
<p>
	Get help on Ruby on Rails Tutorial at the
	<a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
	To get help on this sample app, see the
	<a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/pages/home.html.erb
<h1>Sample App</h1>
<p>
	This is the home page for the <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> sample application.
</p>
<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div class="alert alert-error">
	<h4><%= pluralize(@user.errors.count, "error") %>
	prohibited this user from being saved:</h4>
	<p>
		There were problems with the following fields:
	</p>
	<ul>
		<% @user.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %>
	<%= f.label :name %>
	<%= f.text_field :name, :class=>'input-large' %>
	<%= f.label :email %>
	<%= f.text_field :email, :class=>'input-large' %>
	<%= f.label :password %>
	<%= f.password_field :password, :class=>'input-large' %>
	<%= f.label :password_confirmation, "Confirmation" %>
	<%= f.password_field :password_confirmation, :class=>'input-large' %>
	<div>
	<%= f.submit "Sign up",:class =>'btn btn-primary' %>	
	</div>
<% end %>

app/views/users/show.html.erb
<h1> <%= gravatar_for @user %>
		<%= @user.name %> </h1>
<table class="profile" summary="Profile information">
	<tr>
		<td class="sidebar round"><strong>Name</strong></td><td> <%= @user.name %></td>
	</tr>
	<tr>
		<td><strong>URL</strong></td><td> <%= link_to user_path(@user), @user %> </td>
	</tr>
</table>